apiVersion: v1
kind: Service
metadata:
  name: nodejs-be
  namespace: default
spec:
  selector:
    app: nodejs-be
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: nodejs-be
    protocol: TCP
    port: 80
    targetPort: 3000
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  labels:
    app: be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
      - name: be
        image: docker push truongduyvo/nodejs-be:1.0
        ports:
        - containerPort: 80